spring.application.name=ecommerce

# Configuracion del puerto del servidor
server.port=8081

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceUPB
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate/JPA
# Usamos validate porque la BD ya fue creada con el script SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true