spring.application.name=ecommerce

# Puerto del servidor
server.port=8081

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceUPB
spring.datasource.username=postgres
spring.datasource.password=Ma1098581
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA — validate porque el schema ya existe (creado con el .backup)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
